spring:
  application:
    name: eureka-service
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: user
      password: pass

eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: false
    registerWithEureka: false
    serviceUrl:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-server1:8761/eureka
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-server1:8761/eureka
#      defaultZone: http:/eureka-server1:8761/eureka
---
server:
  port: 8761
spring:
  profiles: server1
eureka:
  instance:
    hostname: eureka-server1

---
server:
  port: 8762
spring:
  profiles: server2
eureka:
  instance:
    hostname: eureka-server2
---
server:
  port: 8763
spring:
  profiles: server3
eureka:
  instance:
    hostname: eureka-server3
---